pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/Collections/*

- script: dotnet restore
  displayName: Restore NuGet packages

- script: dotnet build -c $(buildConfiguration)
  displayName: Build solution

- script: dotnet test
  displayName: Run unit tests

- script: dotnet pack 'src/Collections' -o '$(Build.ArtifactStagingDirectory)/packages/collections' --no-build
  displayName: Create NuGet packages    

- script: dotnet nuget push '$(Build.ArtifactStagingDirectory)/packages/collections/*.nupkg' -k $(nugetApiKey)
  displayName: Publish NuGet packages 